// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcpN0hb3TkrCsQeben2PmgXX4jGVQO7mY',
    appId: '1:486126734960:web:275940d38f3909b129aeb5',
    messagingSenderId: '486126734960',
    projectId: 'finalspractical-14b04',
    authDomain: 'finalspractical-14b04.firebaseapp.com',
    storageBucket: 'finalspractical-14b04.firebasestorage.app',
    measurementId: 'G-X3X603ESWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA-IPK8gQDyM6SZqPM2TJEQmXfwHEFZEI',
    appId: '1:486126734960:android:48ea064ede7b870a29aeb5',
    messagingSenderId: '486126734960',
    projectId: 'finalspractical-14b04',
    storageBucket: 'finalspractical-14b04.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5eY0g30FP2bWkvP9JMjQYu7ave8ovhMI',
    appId: '1:486126734960:ios:2cc4f008461546c529aeb5',
    messagingSenderId: '486126734960',
    projectId: 'finalspractical-14b04',
    storageBucket: 'finalspractical-14b04.firebasestorage.app',
    iosBundleId: 'com.example.finalsPractical',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5eY0g30FP2bWkvP9JMjQYu7ave8ovhMI',
    appId: '1:486126734960:ios:2cc4f008461546c529aeb5',
    messagingSenderId: '486126734960',
    projectId: 'finalspractical-14b04',
    storageBucket: 'finalspractical-14b04.firebasestorage.app',
    iosBundleId: 'com.example.finalsPractical',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcpN0hb3TkrCsQeben2PmgXX4jGVQO7mY',
    appId: '1:486126734960:web:32e5db93e64ab0ad29aeb5',
    messagingSenderId: '486126734960',
    projectId: 'finalspractical-14b04',
    authDomain: 'finalspractical-14b04.firebaseapp.com',
    storageBucket: 'finalspractical-14b04.firebasestorage.app',
    measurementId: 'G-N6NN6FF0XD',
  );
}
